const config=require('../config/config');
const {esc,emoji,h,p,hr,footer,table,button,row}=require('./richMessage');
const {rupiah}=require('../utils/format');

function home(user={}){return [
 h(1,`${emoji('HOME')} NOKTEL STORE`),
 p(`${emoji('USER')} Welcome, <b>${esc(user.first_name||'Customer')}</b>.`),
 p(`${emoji('PRODUCTS')} Choose a product below to start an order.`),
 table([['Service','Availability'],['Regular VPS','DigitalOcean / Linode'],['VPS Legal','DigitalOcean / Linode'],['Noktel','Inventory'],['Script','Catalog']]),
 hr(),
 row(button('Products','home:products','primary','PRODUCTS')),
 row(button('Rating','home:rating','success','STAR'),button('Other...','home:other','primary','SETTINGS')),
 row(button('Support','home:support','primary','SUPPORT'),button('Help','home:help','primary','HELP')),
 footer(`${emoji('INFO')} Secure checkout • Owner verified payment`)
].join('');}
function products(){return [h(1,`${emoji('PRODUCTS')} Product Catalog`),p(`${emoji('INFO')} Select one service.`),table([['Product','Flow'],['Regular VPS','Warranty → Spec → Region → OS'],['VPS Legal','Spec → Region → OS'],['Noktel','Inventory → Payment → Handoff'],['Script','Catalog → Payment → Delivery']]),hr(),row(button('Regular VPS','product:vps','primary','VPS'),button('VPS Legal','product:legal','success','SERVER')),
row(button('Noktel','product:noktel','primary','PRODUCT'),button('Script','product:script','primary','DOWNLOAD')),row(button('Back','home:back','primary','BACK'))].join('');}
function provider(legal=false){return [h(1,`${emoji('SERVER')} ${legal?'VPS Legal':'Regular VPS'} — Provider`),p(`${emoji('INFO')} Select the infrastructure provider.`),table([['Provider','Status'],['DigitalOcean',legal?(config.providers.digitalocean.legalApi?'Configured':'Not configured'):'5 warranty accounts'],['Linode',legal?(config.providers.linode.legalApi?'Configured':'Not configured'):'5 warranty accounts']]),hr(),row(button('DigitalOcean',legal?'legal:provider:digitalocean':'vps:provider:digitalocean','primary','SERVER'),button('Linode',legal?'legal:provider:linode':'vps:provider:linode','primary','SERVER')),row(button('Back','home:products','primary','BACK'))].join('');}
function warranty(provider){const ks=['low','standard','high','super','gold'];return [h(1,`${emoji('SECURITY')} Warranty Package`),p(`${emoji('INFO')} Provider: <b>${esc(provider)}</b>`),table([['Package','Warranty','Replace'],...ks.map(k=>{const w=config.warranty[k];return[w.name,`${w.days} days`,`${w.replace}x`];})]),p(`${emoji('PRICE')} Package fees are configured in <code>harga.env</code>.`),hr(),...ks.map(k=>row(button(config.warranty[k].name,`vps:warranty:${provider}:${k}`,'primary',k==='gold'?'PREMIUM':'SECURITY'))),row(button('Back',`vps:provider:${provider}`,'primary','BACK'))].join('');}
function spec({provider,legal=false}){const plans=[['r8c4','R8C4','8 GB','4 vCPU','80 GB'],['s4c8','S4C8','16 GB','8 vCPU','160 GB'],['h8c16','H8C16','32 GB','16 vCPU','320 GB']];return [h(1,`${emoji('VPS')} ${legal?'Legal VPS':'VPS'} — Specification`),p(`${emoji('SERVER')} Provider: <b>${esc(provider)}</b>`),table([['Plan','RAM','CPU','Disk'],...plans.map(x=>x.slice(1))]),p(`${emoji('PRICE')} ${legal?'Legal':'Regular'} pricing uses the separate namespace in <code>harga.env</code>.`),hr(),...plans.map(x=>row(button(x[1],`${legal?'legal':'vps'}:spec:${provider}:${x[0]}`,'primary','SERVER'))),row(button('Back',legal?`legal:provider:${provider}`:`vps:provider:${provider}`,'primary','BACK'))].join('');}
function region({provider,spec,legal=false}){const rs=provider==='digitalocean'?[['sgp1','Singapore'],['nyc3','New York']]:[['singapore','Singapore'],['newark','Newark']];return [h(1,`${emoji('LINK')} Select Region`),p(`${emoji('SERVER')} Specification: <b>${esc(spec.toUpperCase())}</b>`),table([['Region','Pricing key'],...rs.map(x=>[x[1],`${provider}${legal?'_legal':''}_region_${x[0]}`])]),hr(),...rs.map(x=>row(button(x[1],`${legal?'legal':'vps'}:region:${provider}:${spec}:${x[0]}`,'primary','LINK'))),row(button('Back',`${legal?'legal':'vps'}:spec:${provider}:${spec}`,'primary','BACK'))].join('');}
function os({provider,spec,region,legal=false}){const oss=[['ubuntu','Ubuntu'],['debian','Debian']];return [h(1,`${emoji('SETTINGS')} Operating System`),p(`${emoji('SERVER')} <b>${esc(spec.toUpperCase())}</b> • ${esc(region)}`),table([['OS','Pricing key'],...oss.map(x=>[x[1],`${provider}${legal?'_legal':''}_os_${x[0]}`])]),hr(),...oss.map(x=>row(button(x[1],`${legal?'legal':'vps'}:os:${provider}:${spec}:${region}:${x[0]}`,'primary','SERVER'))),row(button('Back',`${legal?'legal':'vps'}:region:${provider}:${spec}:${region}`,'primary','BACK'))].join('');}
function summary(data){const rows=[['Provider',data.provider],['Specification',data.spec],['Region',data.region],['OS',data.os]];if(data.legal)rows.splice(1,0,['Service','Legal VPS — 1 month']);else{rows.splice(1,0,['Warranty',`${data.warrantyName} — ${data.warrantyDays} days`]);rows.splice(2,0,['Replacement',`${data.replace}x`]);}return [h(1,`${emoji('CHECKOUT')} Order Summary`),p(`${emoji('INFO')} Review before payment.`),table([['Item','Selection'],...rows]),h(3,`${emoji('MONEY')} Total`),p(`<b>${rupiah(data.total)}</b>`),table([['Component','Amount'],...(data.feeItems||[]).map(x=>[x.label,rupiah(x.amount)])]),hr(),row(button('Confirm & Pay',`order:confirm:${data.id}`,'success','PAYMENT')),row(button('Edit','home:products','primary','EDIT'),button('Cancel','home:back','danger','CROSS'))].join('');}
function payment(order){const ms=[];if(config.payment.qris)ms.push(['QRIS','Configured']);for(const m of config.payment.methods)ms.push([m.name,m.number]);return [h(1,`${emoji('PAYMENT')} Payment`),p(`${emoji('MONEY')} Amount: <b>${rupiah(order.total)}</b>`),table([['Method','Destination'],...(ms.length?ms:[['Payment','No method configured']])]),p(`${emoji('UPLOAD')} Send your payment proof as a photo after paying.`),p(`${emoji('ORDER')} Order: <code>${esc(order.id)}</code>`),hr(),row(button('Refresh','product:noktel','primary','REFRESH'),button('Support','home:support','primary','SUPPORT')),row(button('Cancel','home:back','danger','CROSS'))].join('');}
function support(){return [h(1,`${emoji('SUPPORT')} Support Center`),p(`${emoji('INFO')} Choose the assistance you need.`),h(3,`${emoji('MESSAGE')} Chat Admin`),p('Talk to the owner through the bot relay.'),h(3,`${emoji('REFERRAL')} Minta Reff`),p('Request a referral/reff for a product.'),h(3,`${emoji('REFRESH')} VPS Replace`),p('Submit Order ID, terminal screenshot, chronology, and current situation.'),hr(),row(button('Chat Admin','support:chat','primary','MESSAGE')),row(button('Minta Reff','support:reff','success','REFERRAL')),row(button('VPS Replace','support:replace','primary','REFRESH')),row(button('Back','home:back','primary','BACK'))].join('');}
function help(){return [h(1,`${emoji('HELP')} Help`),p(`${emoji('INFO')} Products are ordered through the catalog. Payment proofs are reviewed by the owner.`),table([['Feature','How it works'],['VPS','Configure → Pay → Proof → Owner → Provision'],['Noktel','Choose inventory → Pay → Owner handoff'],['Script','Choose script → Pay → Owner confirms → Delivery'],['Support','Relay, reff, or VPS replacement']]),hr(),row(button('Back','home:back','primary','BACK'))].join('');}
function rating(){return [h(1,`${emoji('STAR')} Rate Your Experience`),p(`${emoji('INFO')} Select your score.`),table([['Score','Level'],['1 Star','Worst Order'],['2 Stars','Bad News'],['3 Stars','Need improve'],['4 Stars','Good Score'],['5 Stars','Great Score!']]),hr(),row(button('1','rating:score:1','danger','STAR'),button('2','rating:score:2','danger','STAR')),row(button('3','rating:score:3','primary','STAR'),button('4','rating:score:4','success','STAR')),row(button('5','rating:score:5','success','STAR')),row(button('Back','home:back','primary','BACK'))].join('');}
function ratingFeedback(score){const labels={1:'Worst Order',2:'Bad News',3:'Need improve',4:'Good Score',5:'Great Score!'};return [h(1,`${emoji('STAR')} ${labels[score]}`),p(`${emoji('MESSAGE')} Score: <b>${score} Stars</b>`),p('Please send your feedback as a message. It will be sent to the owner and transaction archive channel.'),hr(),row(button('Skip','home:back','primary','BACK'),button('Cancel','home:back','danger','CROSS'))].join('');}
function other(){return [h(1,`${emoji('SETTINGS')} Other...`),p(`${emoji('INFO')} Fun utilities and generators.`),table([['Command','Output'],['/fakedana','Fake DANA image'],['/brat','Brat sticker'],['/fakeff','Fake FF image'],['/quotesbook','Quote image'],['/fakerip','RIP image']]),hr(),row(button('Back','home:back','primary','BACK'))].join('');}
function noktel(items=[]){const rows=[['Noktel','Harga'],...items.map(x=>[x.name||x.number,rupiah(x.price)])];return [h(1,`${emoji('PRODUCT')} Noktel`),p(`${emoji('INFO')} Select an available Noktel.`),table(rows.length>1?rows:[['Noktel','Inventory empty']]),hr(),...items.map(x=>row(button(`${x.name||x.number} • ${rupiah(x.price)}`,`noktel:buy:${x.id}`,'success','PRODUCT'))),row(button('Refresh','product:noktel','primary','REFRESH')),row(button('Back','home:products','primary','BACK'))].join('');}
function script(items=[]){const rows=[['Script','Harga'],...items.map(x=>[x.name,rupiah(Number(String(x.price).replace(/\./g,'')))])];return [h(1,`${emoji('DOWNLOAD')} Script Catalog`),p(`${emoji('INFO')} Choose a script.`),table(rows.length>1?rows:[['Script','Catalog empty']]),hr(),...items.map(x=>row(button(`${x.name} • ${rupiah(Number(String(x.price).replace(/\./g,'')))}`,`script:buy:${x.id}`,'success','DOWNLOAD'))),row(button('Refresh','product:script','primary','REFRESH')),row(button('Back','home:products','primary','BACK'))].join('');}
module.exports={home,products,provider,warranty,spec,region,os,summary,payment,support,help,rating,ratingFeedback,other,noktel,script};
